name: dolphin-env
channels:
  - conda-forge
dependencies:
  - python>=3.7,<3.11
  - pip
  - gdal>=3.3
  - git  # For pip-installing in the Docker image
  - h5py
  - numba
  - numpy
  - pydantic
  - pymp-pypi
  - ruamel.yaml
  - scipy>=1.5 # "scipy 0.16+ is required for linear algebra", numba. 1.5 is the oldest version that supports Python 3.7
