name: dolphin-env
channels:
  - conda-forge
dependencies:
  - python>=3.8
  - pip>=21.3  # https://pip.pypa.io/en/stable/reference/build-system/pyproject-toml/#editable-installation
  - git  # for pip install, due to setuptools_scm
  - isce3
  - gdal>=3.3
  - h5py>=3.6
  - hdf5!=1.12.2 # https://github.com/SciTools/iris/issues/5187 and https://github.com/pydata/xarray/issues/7549
  - numba>=0.54
  - numpy>=1.20
  - pydantic>=2.1
  - pymp-pypi>=0.4.5
  - pyproj>=3.3
  - rich>=12.0
  - ruamel.yaml>=0.15
  - scipy>=1.5 # "scipy 0.16+ is required for linear algebra", numba. 1.5 is the oldest version that supports Python 3.7
  - shapely>=1.8
  - tbb>=2021.6.0 # Module for numba threading which prevents `fork()` crashes
  - threadpoolctl>=3.0
