SPEED_OF_LIGHT = 299_792_458  # meters / second

SENTINEL_1_FREQUENCY = 5.405e9  # Hz
SENTINEL_1_WAVELENGTH = SPEED_OF_LIGHT / SENTINEL_1_FREQUENCY  # meters

NISAR_L_FREQUENCY = 1.25e9  # Hz
NISAR_S_FREQUENCY = 3.2e9  # Hz
NISAR_L_WAVELENGTH = SPEED_OF_LIGHT / NISAR_L_FREQUENCY  # meters
NISAR_S_WAVELENGTH = SPEED_OF_LIGHT / NISAR_S_FREQUENCY  # meters
